# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
baseURL = "/"
canonifyURLs = false
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "dnduchuy08@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
[Languages]
[Languages.en]
title = "AWS KMS Workshop"
weight = 1
languageName = "English"
languageCode = "en"
contentDir = "content/en"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "http://awsstudygroup.com"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/660548818043427/"
weight = 20

[Languages.vi]
title = "AWS KMS Workshop"
weight = 2
languageName = "Tiếng Việt"
languageCode = "vi"
contentDir = "content/vi"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "http://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/660548818043427/"
weight = 20

